apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: 393385300479.dkr.ecr.ap-south-1.amazonaws.com/my-app:latest
        ports:
        - containerPort: 80

